-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https//github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local function augroup(name)
--   return vim.api.nvim_create_augroup("lazyvim_" .. name, { clear = true })
-- end
--
-- vim.api.nvim_create_autocmd({ "BufRead", "BufNewFile", "FileType" }, {
--   group = augroup("jenkinsfile"),
--   pattern = { "Jenkinsfile*" },
--   callback = function()
--     vim.opt_local.filetype = "groovy"
--     vim.opt_local.shiftwidth = 4
--     vim.opt_local.tabstop = 4
--   end,
-- })
