theme = "catppuccin_mocha"

[keys.insert]
j = {k = "normal_mode"}
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
ret = ["move_line_down", "goto_line_start"]

[keys.normal.space]
q = ":quit"

[keys.normal.space.f]
s = ":write"
f = "file_picker"

[keys.select]
esc = ["collapse_selection", "normal_mode"]

[editor]
auto-save = true
bufferline = "always"
line-number = "relative"
# rulers = [120]
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.soft-wrap]
enable = true

[editor.statusline]
center = ["version-control"]

[editor.lsp]
display-inlay-hints = true
auto-signature-help = true
