theme = "nightfox"

[keys.insert]
j = {k = "normal_mode"}
esc = ["collapse_selection", "normal_mode"]
S-tab = "move_parent_node_start"

[keys.select]
esc = ["collapse_selection", "normal_mode"]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"
a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
ret = ["move_line_down", "goto_line_start"]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.space]
q = {q = ":quit-all"}

[keys.normal.space.f]
s = ":write"
f = "file_picker"

[editor]
auto-save = true
bufferline = "never"
line-number = "relative"
undercurl = true
color-modes = true
# rulers = [120]
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
